// <auto-generated />
using System;
using CoffeeLovers.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeLovers.DAL.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    partial class CoffeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeLovers.DomainModels.Models.Area", b =>
                {
                    b.Property<Guid>("AreaId");

                    b.Property<string>("AreaDisplayId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Createdtime");

                    b.Property<bool>("IsActive");

                    b.Property<int>("PinCode");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Updatedtime");

                    b.HasKey("AreaId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("CoffeeLovers.DomainModels.Models.Coffee", b =>
                {
                    b.Property<Guid>("CoffeeId");

                    b.Property<string>("CoffeeDisplayId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("CoffeeName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Createdtime");

                    b.Property<bool>("IsActive");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Updatedtime");

                    b.Property<DateTime>("validFrom");

                    b.Property<DateTime>("validTo");

                    b.HasKey("CoffeeId");

                    b.ToTable("Coffee");
                });

            modelBuilder.Entity("CoffeeLovers.DomainModels.Models.Owner", b =>
                {
                    b.Property<Guid>("OwnerId");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Createdtime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("OwnerDisplayId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("Updatedtime");

                    b.HasKey("OwnerId");

                    b.ToTable("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
